---
name: Run tests and create release

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

permissions:
  contents: write

jobs:
  php-run-tests:
    uses: ./.github/workflows/_php-run-tests.yml

  github-create-release:
    needs: php-run-tests
    uses: ./.github/workflows/_github-create-release.yml
